version: '3.1'

services:

  app:
    build: .
    ports:
      - 8080:80

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app    
